'use client';

import { useCallback, useMemo, useState } from 'react';
import { WidgetFrame } from '@/components/sim/widget-frame';
import { SimCanvas } from '@/components/sim/sim-canvas';
import { ActionButton, ButtonRow, ControlPanel, Slider, Toggle, Transport } from '@/components/sim/controls';
import { HeatMap, StatTile } from '@/components/viz';
import { useSimulation } from '@/lib/sim/use-simulation';
import { Kf, type Gaussian } from '@/lib/filters/kf';
import { chi2Envelope, nees, nis, rmse } from '@/lib/filters/consistency';
import { sampleMvn } from '@/lib/prob/gaussian';
import { Rng } from '@/lib/prob/rng';
import { matVec, type Mat, type Vec } from '@/lib/prob/linalg';
import { clear, label, sx, sy, type Palette, type Viewport } from '@/lib/sim/draw';

/**
 * w6.1 — the Kalman Tuning Bench.
 *
 * Rusty's cart on a rail, tracked by the real `Kf` from the library. The whole
 * chapter is visible in one frame: a blue prior, an orange prediction that is
 * wider than it, a green measurement likelihood, and a purple posterior that is
 * tighter than either parent.
 *
 * The two sliders are the two lies a filter designer can tell. R says how much
 * the cart is trusted to obey the model; Q says how much the sensor is trusted.
 * Neither changes the truth — only what the filter believes about it — which is
 * why the divergence preset produces a filter that is confidently, measurably
 * wrong while its RMSE still looks respectable for a while.
 */

const DT = 0.1;
const WINDOW = 170;
const RUN_LENGTH = 420;
/** Canvas aspect. The world rectangle is ASPECT×1 so [0,1]² maps pixel-exact. */
const ASPECT = 2.15;

/** Truth is generated by the same linear-Gaussian model the filter assumes, so
 *  any inconsistency the bench shows is the *tuning's* fault, not the model's. */
const TRUE_ACCEL_SIGMA = 0.45; // m/s², the slip the cart really has
const TRUE_MEAS_SIGMA = 0.32; // m, the noise the pings really have

interface Params {
  /** Thrun's R_t, as an acceleration σ. Bigger ⇒ "my model is a guess". */
  accelSigma: number;
  /** Thrun's Q_t, as a range σ. Bigger ⇒ "my sensor is a liar". */
  measSigma: number;
  sweep: boolean;
  sweepMetric: 'rmse' | 'nis';
}

interface Sample {
  t: number;
  truth: number;
  z: number;
  prior: number;
  priorSd: number;
  post: number;
  postSd: number;
}

interface State {
  rng: Rng;
  kf: Kf;
  truth: Vec;
  /** Belief at the three moments of one cycle, for the blob panel. */
  before: Gaussian;
  predicted: Gaussian;
  z: number;
  gain: number;
  samples: Sample[];
  neesHist: number[];
  nisHist: number[];
  errHist: number[];
  gainHist: number[];
}

/* -------------------------------------------------------------------------- */
/* The linear-Gaussian model                                                   */
/* -------------------------------------------------------------------------- */

const F: Mat = [
  [1, DT],
  [0, 1],
];
const H: Mat = [[1, 0]];

/** Thrun's R_t: the discrete white-acceleration process noise, σ_a² · [[dt³/3, dt²/2], [dt²/2, dt]]. */
function motionNoise(accelSigma: number): Mat {
  const q = accelSigma * accelSigma;
  return [
    [(q * DT ** 3) / 3, (q * DT ** 2) / 2],
    [(q * DT ** 2) / 2, q * DT],
  ];
}

/** Thrun's Q_t for a single position ping. */
const measNoise = (sigma: number): Mat => [[sigma * sigma]];

/**
 * The failure gallery — same numbers as the chapter text and the Rust tests.
 * Each preset moves exactly one knob away from `balanced`, so whatever the
 * meters do is attributable to that knob alone.
 */
const PRESETS: { name: string; accelSigma: number; measSigma: number }[] = [
  { name: 'balanced', accelSigma: TRUE_ACCEL_SIGMA, measSigma: TRUE_MEAS_SIGMA },
  { name: 'sluggish', accelSigma: TRUE_ACCEL_SIGMA, measSigma: 2.4 },
  { name: 'jittery', accelSigma: 4.0, measSigma: TRUE_MEAS_SIGMA },
  { name: 'divergent', accelSigma: 0.004, measSigma: TRUE_MEAS_SIGMA },
];

export function KalmanTuningBench() {
  const [params, setParams] = useState<Params>({
    accelSigma: TRUE_ACCEL_SIGMA,
    measSigma: TRUE_MEAS_SIGMA,
    sweep: false,
    sweepMetric: 'rmse',
  });

  const init = useCallback((seed: number): State => {
    const rng = new Rng(seed);
    const kf = new Kf([0, 0], [
      [1, 0],
      [0, 1],
    ]);
    return {
      rng,
      kf,
      truth: [0, 0.7],
      before: kf.belief(),
      predicted: kf.belief(),
      z: 0,
      gain: 0,
      samples: [],
      neesHist: [],
      nisHist: [],
      errHist: [],
      gainHist: [],
    };
  }, []);

  const step = useCallback(
    (s: State, tick: number): State => {
      const { rng, kf } = s;
      const before = kf.belief();

      // ---- the world moves, honestly ------------------------------------
      const truth = matVec(F, s.truth);
      const w = sampleMvn([0, 0], motionNoise(TRUE_ACCEL_SIGMA), rng);
      truth[0] += w[0];
      truth[1] += w[1];
      const z = truth[0] + rng.normal(0, TRUE_MEAS_SIGMA);

      // ---- the filter predicts ------------------------------------------
      // NOTE the argument names: the library follows the control-theory
      // convention (Q on predict, R on update); the book follows Thrun's
      // (R on motion, Q on measurement). Same matrices, opposite letters.
      kf.predictWith(F, motionNoise(params.accelSigma));
      const predicted = kf.belief();

      // ---- and corrects --------------------------------------------------
      const info = kf.updateWith([z], H, measNoise(params.measSigma));
      const posterior = kf.belief();

      const sample: Sample = {
        t: tick,
        truth: truth[0],
        z,
        prior: predicted.x[0],
        priorSd: Math.sqrt(predicted.P[0][0]),
        post: posterior.x[0],
        postSd: Math.sqrt(posterior.P[0][0]),
      };

      return {
        rng,
        kf,
        truth,
        before,
        predicted,
        z,
        gain: info.K[0][0],
        samples: [...s.samples, sample].slice(-WINDOW),
        neesHist: [...s.neesHist, nees(truth, posterior)].slice(-60),
        nisHist: [...s.nisHist, nis(info.innovation, info.S)].slice(-60),
        errHist: [...s.errHist, posterior.x[0] - truth[0]].slice(-60),
        gainHist: [...s.gainHist, info.K[0][0]].slice(-60),
      };
    },
    [params.accelSigma, params.measSigma],
  );

  const sim = useSimulation<State>({ init, step, fps: 14, maxTicks: RUN_LENGTH, loop: true, initialSeed: 7 });

  /* ------------------------------------------------------------------ */
  /* Drawing                                                             */
  /* ------------------------------------------------------------------ */

  const draw = useCallback(
    (ctx: CanvasRenderingContext2D, v: Viewport, p: Palette) => {
      clear(ctx, v, p);
      const { samples, before, predicted, z } = sim.state;
      if (samples.length < 2) return;

      // Normalized panel coordinates: the whole widget lives in [0,1]².
      const px = (u: number) => sx(v, u * ASPECT);
      const py = (u: number) => sy(v, u);

      // A shared position window keeps the rail and the strip chart in register.
      let lo = Infinity;
      let hi = -Infinity;
      for (const s of samples) {
        lo = Math.min(lo, s.truth, s.z, s.post - 2 * s.postSd);
        hi = Math.max(hi, s.truth, s.z, s.post + 2 * s.postSd);
      }
      const pad = 0.12 * (hi - lo) + 0.2;
      lo -= pad;
      hi += pad;
      const pos = (m: number) => (m - lo) / (hi - lo);

      const last = samples[samples.length - 1];

      /* ---- top panel: the rail and four blobs --------------------------
         This panel gets its own, much tighter window. Over 170 steps the cart
         wanders metres, and at that scale four beliefs a few centimetres wide
         are one indistinguishable spike — so the blob view zooms in on the
         current step and prints the span it is showing. */
      const sdPrior = Math.sqrt(before.P[0][0]);
      const sdPred = Math.sqrt(predicted.P[0][0]);
      const sdMeas = params.measSigma;
      const sdPost = last.postSd;

      const center = (predicted.x[0] + z) / 2;
      const spread = Math.max(
        3.2 * Math.max(sdPrior, sdPred, sdMeas, sdPost),
        1.5 * Math.abs(z - predicted.x[0]),
        0.4,
      );
      const zlo = center - spread;
      const zhi = center + spread;
      const zpos = (m: number) => Math.max(0, Math.min(1, (m - zlo) / (zhi - zlo)));

      const railY = 0.955;
      ctx.strokeStyle = p.grid;
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(px(0.02), py(railY));
      ctx.lineTo(px(0.98), py(railY));
      ctx.stroke();

      // The cart Rusty is riding — gray, because the filter never sees it.
      const cartX = px(0.02 + 0.96 * zpos(last.truth));
      ctx.fillStyle = p.truth;
      ctx.fillRect(cartX - 7, py(railY) - 9, 14, 9);
      label(ctx, 'truth', cartX, py(railY) - 17, p.truth, { size: 9, align: 'center' });
      label(ctx, `zoom: ${(2 * spread).toFixed(2)} m across`, px(0.98), py(railY) - 17, p.ink, {
        size: 9,
        align: 'right',
      });

      const blobTop = 0.905;
      const blobBase = 0.70;
      const bell = (mean: number, sd: number, scale: number, color: string, dashed = false) => {
        ctx.save();
        ctx.strokeStyle = color;
        ctx.lineWidth = 1.9;
        if (dashed) ctx.setLineDash([4, 3]);
        ctx.beginPath();
        for (let i = 0; i <= 200; i++) {
          const u = i / 200;
          const m = zlo + u * (zhi - zlo);
          const d = (m - mean) / sd;
          const h = (Math.exp(-0.5 * d * d) / sd) * scale;
          const x = px(0.02 + 0.96 * u);
          const y = py(blobBase + Math.min(h, 1) * (blobTop - blobBase));
          if (i === 0) ctx.moveTo(x, y);
          else ctx.lineTo(x, y);
        }
        ctx.stroke();
        ctx.restore();
      };

      // One shared vertical scale, so a tighter blob is genuinely taller —
      // height is precision, and precision is the quantity the gain weighs.
      const peak = Math.max(1 / sdPrior, 1 / sdPred, 1 / sdMeas, 1 / sdPost);
      const scale = 1 / peak;

      bell(before.x[0], sdPrior, scale, p.prior);
      bell(predicted.x[0], sdPred, scale, p.prediction);
      bell(z, sdMeas, scale, p.measurement, true);
      bell(last.post, sdPost, scale, p.posterior);

      label(ctx, 'prior', px(0.03), py(blobTop - 0.005), p.prior, { size: 9 });
      label(ctx, 'prediction', px(0.115), py(blobTop - 0.005), p.prediction, { size: 9 });
      label(ctx, 'measurement', px(0.245), py(blobTop - 0.005), p.measurement, { size: 9 });
      label(ctx, 'posterior', px(0.40), py(blobTop - 0.005), p.posterior, { size: 9 });

      /* ---- bottom panel: the strip chart -------------------------------- */
      const chartTop = 0.62;
      const chartBot = 0.05;
      const tx = (i: number) => px(0.02 + 0.96 * (i / (WINDOW - 1)));
      const ty = (m: number) => py(chartBot + pos(m) * (chartTop - chartBot));

      ctx.strokeStyle = p.grid;
      ctx.lineWidth = 1;
      ctx.strokeRect(px(0.02), py(chartTop), px(0.98) - px(0.02), py(chartBot) - py(chartTop));

      // The ±2σ band the filter claims about position.
      ctx.fillStyle = p.posterior;
      ctx.globalAlpha = 0.15;
      ctx.beginPath();
      samples.forEach((s, i) => {
        const y = ty(s.post + 2 * s.postSd);
        if (i === 0) ctx.moveTo(tx(i), y);
        else ctx.lineTo(tx(i), y);
      });
      for (let i = samples.length - 1; i >= 0; i--) {
        ctx.lineTo(tx(i), ty(samples[i].post - 2 * samples[i].postSd));
      }
      ctx.closePath();
      ctx.fill();
      ctx.globalAlpha = 1;

      // Measurements: what the filter is actually fed.
      ctx.fillStyle = p.measurement;
      ctx.globalAlpha = 0.75;
      samples.forEach((s, i) => {
        ctx.beginPath();
        ctx.arc(tx(i), ty(s.z), 1.5, 0, Math.PI * 2);
        ctx.fill();
      });
      ctx.globalAlpha = 1;

      // Truth, dashed and gray, as always.
      ctx.strokeStyle = p.truth;
      ctx.lineWidth = 1.5;
      ctx.setLineDash([5, 4]);
      ctx.beginPath();
      samples.forEach((s, i) => {
        const y = ty(s.truth);
        if (i === 0) ctx.moveTo(tx(i), y);
        else ctx.lineTo(tx(i), y);
      });
      ctx.stroke();
      ctx.setLineDash([]);

      // The estimate.
      ctx.strokeStyle = p.posterior;
      ctx.lineWidth = 2;
      ctx.beginPath();
      samples.forEach((s, i) => {
        const y = ty(s.post);
        if (i === 0) ctx.moveTo(tx(i), y);
        else ctx.lineTo(tx(i), y);
      });
      ctx.stroke();

      // Mark every step where the truth escapes the filter's own 2σ band.
      ctx.fillStyle = p.prediction;
      samples.forEach((s, i) => {
        if (Math.abs(s.truth - s.post) <= 2 * s.postSd) return;
        ctx.beginPath();
        ctx.arc(tx(i), ty(s.truth), 2.4, 0, Math.PI * 2);
        ctx.fill();
      });

      label(ctx, 'position (m) vs. time', px(0.035), py(chartTop) + 11, p.ink, { size: 9 });
    },
    [sim.state, params.measSigma],
  );

  /* ------------------------------------------------------------------ */
  /* Readouts                                                            */
  /* ------------------------------------------------------------------ */

  // χ² quantiles depend only on how many samples have accumulated, so they are
  // memoized apart from the per-frame statistics.
  const nSamples = Math.max(sim.state.nisHist.length, 1);
  const envelopes = useMemo(
    () => ({ nees: chi2Envelope(2, nSamples), nis: chi2Envelope(1, nSamples) }),
    [nSamples],
  );

  const stats = useMemo(() => {
    const { neesHist, nisHist, errHist, gainHist } = sim.state;
    const mean = (a: number[]) => (a.length ? a.reduce((x, y) => x + y, 0) / a.length : 0);
    const neesMean = mean(neesHist);
    const nisMean = mean(nisHist);
    return {
      gain: sim.state.gain,
      rmse: rmse(errHist),
      neesMean,
      nisMean,
      neesOk: neesHist.length < 12 || (neesMean >= envelopes.nees.lo && neesMean <= envelopes.nees.hi),
      nisOk: nisHist.length < 12 || (nisMean >= envelopes.nis.lo && nisMean <= envelopes.nis.hi),
      gainSpark: gainHist.slice(-40),
      nisSpark: nisHist.slice(-40),
    };
  }, [sim.state, envelopes]);

  /* ------------------------------------------------------------------ */
  /* Sweep mode: the same filter, run offline over an (R, Q) grid         */
  /* ------------------------------------------------------------------ */

  const sweep = useMemo(() => (params.sweep ? runSweep(sim.seed) : null), [params.sweep, sim.seed]);

  const sweepMatrix = useMemo(() => {
    if (!sweep) return null;
    return params.sweepMetric === 'rmse' ? sweep.rmse : sweep.nis.map((row) => row.map((x) => x - 1));
  }, [sweep, params.sweepMetric]);

  return (
    <WidgetFrame
      id="w6.1"
      title="The Kalman Tuning Bench"
      teaches="The gain is not a knob. R and Q are the knobs, and turning them the wrong way makes a filter confident rather than accurate."
      colorKey={['prior', 'prediction', 'measurement', 'posterior', 'truth']}
      wide
      caption={
        <>
          Rusty&rsquo;s cart drifts along a rail; a beacon pings its position with real noise of
          σ&nbsp;=&nbsp;0.32&nbsp;m and the cart really does slip with σ<sub>a</sub>&nbsp;=&nbsp;0.45&nbsp;m/s².
          The top strip is a zoomed view of the current step — a metre or less across, with the span
          printed on the right — showing one cycle as four blobs: the blue prior, the orange
          prediction (always wider, since motion only ever costs information), the green measurement
          likelihood, and the purple posterior, which is <em>taller than both its parents</em>
          because precisions add. The chart beneath it is the last 170 steps at full scale.
          Watch the gain settle to a constant even though no measurement has told it to: Σ, and hence
          K, never depend on the data. Then press <strong>divergent</strong>: the covariance
          collapses, the filter stops listening, and the NIS meter leaves its envelope around twenty
          steps before the RMSE readout looks alarming. Each preset moves exactly one slider away
          from <strong>balanced</strong>, so whatever the meters do is that slider&rsquo;s fault.
          Turn on <strong>sweep</strong> to run the whole (R,&nbsp;Q) plane offline and find the
          region where RMSE is poor but the filter is being perfectly honest about it.
        </>
      }
    >
      {params.sweep && sweepMatrix ? (
        <div className="px-3 pt-3">
          <HeatMap
            matrix={sweepMatrix}
            rowLabels={SWEEP_ACCEL.map((a) => `R σa=${a.toFixed(2)}`)}
            colLabels={SWEEP_MEAS.map((m) => `${m.toFixed(2)}`)}
            diverging={params.sweepMetric === 'nis'}
            valueLabel={params.sweepMetric === 'rmse' ? 'position RMSE (m)' : 'mean NIS − 1 (0 = honest)'}
            precision={2}
            height={300}
            showValues
            caption={
              params.sweepMetric === 'rmse'
                ? 'Position RMSE over 300 steps, one seeded run per cell. Columns are the claimed measurement σ (Thrun’s Q); rows the claimed acceleration σ (Thrun’s R).'
                : 'Mean NIS minus its expected value of 1. Positive (orange) means the filter is overconfident: innovations are larger than the S it predicts. Negative (blue) means it is needlessly timid.'
            }
          />
        </div>
      ) : (
        <SimCanvas
          world={{ minX: 0, maxX: ASPECT, minY: 0, maxY: 1 }}
          draw={draw}
          deps={[sim.tick, sim.state, params.measSigma]}
          aspect={ASPECT}
          padding={0}
          ariaLabel="A rail with a cart above four overlapping bell curves — prior, prediction, measurement and posterior — and beneath it a strip chart of the cart's true position, its noisy measurements, and the filter's estimate with a two-sigma confidence band."
        />
      )}

      <div className="grid grid-cols-2 gap-2 border-t border-fd-border p-3 sm:grid-cols-4">
        <StatTile
          label="Kalman gain K (position)"
          value={stats.gain}
          precision={3}
          role="posterior"
          sparkline={stats.gainSpark}
        />
        <StatTile label="position RMSE" value={stats.rmse} unit="m" precision={3} role="truth" />
        <StatTile
          label="mean NEES (want ≈ 2)"
          value={stats.neesMean}
          precision={2}
          role={stats.neesOk ? undefined : 'prediction'}
        />
        <StatTile
          label="mean NIS (want ≈ 1)"
          value={stats.nisMean}
          precision={2}
          role={stats.nisOk ? undefined : 'prediction'}
          sparkline={stats.nisSpark}
        />
      </div>

      <div className="border-t border-fd-border px-3 py-2 font-ui text-[0.72rem] text-fd-muted-foreground">
        95% envelope for the running average:{' '}
        <span className="font-mono">
          NEES ∈ [{envelopes.nees.lo.toFixed(2)}, {envelopes.nees.hi.toFixed(2)}]
        </span>
        {'  ·  '}
        <span className="font-mono">
          NIS ∈ [{envelopes.nis.lo.toFixed(2)}, {envelopes.nis.hi.toFixed(2)}]
        </span>
        {stats.nisOk ? null : (
          <strong style={{ color: 'var(--pr-prediction)' }}> — the filter is inconsistent.</strong>
        )}
      </div>

      <ControlPanel columns={2}>
        <Slider
          label="measurement noise Q — trust in the sensor (σ_z)"
          role="measurement"
          value={params.measSigma}
          min={0.02}
          max={3}
          step={0.01}
          unit="m"
          onChange={(v) => setParams((p) => ({ ...p, measSigma: v }))}
          help="Thrun's Q_t. The sensor's real σ is 0.32 m; claiming more makes the filter sluggish, claiming less makes it chase noise."
        />
        <Slider
          label="motion noise R — trust in the model (σ_a)"
          role="prediction"
          value={params.accelSigma}
          min={0.004}
          max={4}
          step={0.004}
          unit="m/s²"
          onChange={(v) => setParams((p) => ({ ...p, accelSigma: v }))}
          help="Thrun's R_t, as an acceleration σ. The cart's real slip is 0.45 m/s²."
        />
      </ControlPanel>

      <div className="flex flex-wrap items-center gap-2 border-t border-fd-border px-3 py-2">
        <span className="eyebrow">presets</span>
        <ButtonRow>
          {PRESETS.map((preset) => (
            <ActionButton
              key={preset.name}
              onClick={() =>
                setParams((p) => ({ ...p, accelSigma: preset.accelSigma, measSigma: preset.measSigma }))
              }
            >
              {preset.name}
            </ActionButton>
          ))}
        </ButtonRow>
        <div className="ms-auto flex items-center gap-3">
          <Toggle
            label="sweep (R, Q)"
            checked={params.sweep}
            onChange={(v) => setParams((p) => ({ ...p, sweep: v }))}
          />
          {params.sweep ? (
            <Toggle
              label="show NIS instead of RMSE"
              checked={params.sweepMetric === 'nis'}
              onChange={(v) => setParams((p) => ({ ...p, sweepMetric: v ? 'nis' : 'rmse' }))}
            />
          ) : null}
        </div>
      </div>

      <Transport
        playing={sim.playing}
        onToggle={sim.toggle}
        onStep={sim.stepOnce}
        onReset={sim.reset}
        onReseed={() => sim.reseed()}
        seed={sim.seed}
        tick={sim.tick}
        speed={sim.speed}
        onSpeed={sim.setSpeed}
      />
    </WidgetFrame>
  );
}

/* -------------------------------------------------------------------------- */
/* Offline sweep                                                              */
/* -------------------------------------------------------------------------- */

const SWEEP_ACCEL = [0.004, 0.02, 0.09, 0.45, 1.4, 4.0];
const SWEEP_MEAS = [0.03, 0.1, 0.32, 0.9, 2.4];
const SWEEP_STEPS = 300;

/**
 * The ladder of abstraction: instead of one run at one setting, run the same
 * seeded trajectory through every (R, Q) pair and look at the landscape. Cheap
 * enough to do synchronously — 30 cells × 300 steps of 2×2 algebra.
 */
function runSweep(seed: number) {
  const rmseGrid: number[][] = [];
  const nisGrid: number[][] = [];

  for (const accel of SWEEP_ACCEL) {
    const rmseRow: number[] = [];
    const nisRow: number[] = [];
    for (const meas of SWEEP_MEAS) {
      // Same seed everywhere: every cell sees the identical world.
      const rng = new Rng(seed);
      const kf = new Kf([0, 0], [
        [1, 0],
        [0, 1],
      ]);
      let truth: Vec = [0, 0.7];
      const errs: number[] = [];
      let nisSum = 0;

      for (let k = 0; k < SWEEP_STEPS; k++) {
        truth = matVec(F, truth);
        const w = sampleMvn([0, 0], motionNoise(TRUE_ACCEL_SIGMA), rng);
        truth[0] += w[0];
        truth[1] += w[1];
        const z = truth[0] + rng.normal(0, TRUE_MEAS_SIGMA);

        kf.predictWith(F, motionNoise(accel));
        const info = kf.updateWith([z], H, measNoise(meas));
        errs.push(kf.x[0] - truth[0]);
        nisSum += nis(info.innovation, info.S);
      }

      rmseRow.push(rmse(errs));
      nisRow.push(nisSum / SWEEP_STEPS);
    }
    rmseGrid.push(rmseRow);
    nisGrid.push(nisRow);
  }

  return { rmse: rmseGrid, nis: nisGrid };
}
