'use client';

import { useCallback, useMemo, useState } from 'react';
import { WidgetFrame } from '@/components/sim/widget-frame';
import { SimCanvas } from '@/components/sim/sim-canvas';
import { ActionButton, ButtonRow, ControlPanel, Slider, Toggle, Transport } from '@/components/sim/controls';
import { useSimulation } from '@/lib/sim/use-simulation';
import { Rng } from '@/lib/prob/rng';
import { APARTMENT, rayCast } from '@/lib/sim/world';
import { beamLikelihood, type BeamParams } from '@/lib/models/sensor';
import { beamComponents, emStep } from '@/lib/models/beam-em';
import { clear, label, sl, sx, sy, type Palette, type Viewport } from '@/lib/sim/draw';

/**
 * w10.1 — the Beam Mixture Mixer.
 *
 * One beam, fired down the Apartment's corridor ten thousand times. The
 * histogram that builds up is not a Gaussian and never was: it has a hump at
 * the wall, a shoulder in front of it, a spike at z_max and a floor everywhere
 * else. Four physical causes, four densities, one mixture.
 *
 * Everything on screen is generated by *geometry and physics*, not by the model
 * being fitted: the wall comes from `rayCast` into the real map, the shoulder
 * from a Poisson clutter field along the ray (whose nearest hit is exactly
 * exponential — that is where p_short comes from), the spike from a dropout
 * probability, the floor from crosstalk. EM then has to recover the four
 * weights from the data alone, and the readout compares what it found with what
 * the generator actually did.
 */

const BINS = 90;
const BATCH = 90;
const TARGET = 4500;
const EM_ITERS = 24;
const MAX_RANGE = 8;

/**
 * Rusty parked in the corridor outside room A, one beam aimed south through the
 * doorway at the apartment's far wall: z* = 4.4 m, comfortably inside the
 * sensor's 8 m range, with enough room in front of the wall for clutter and
 * enough behind it for the uniform floor to be visible.
 */
const SENSOR = { x: 2.05, y: 4.4, theta: -Math.PI / 2 };
const Z_STAR = rayCast(APARTMENT, SENSOR.x, SENSOR.y, SENSOR.theta, MAX_RANGE);

/** The physical process the sensor actually obeys — none of these are Θ. */
interface Physics {
  /** Beams lost to an absorptive or specular-away surface. */
  dropout: number;
  /** Beams corrupted by crosstalk or multipath: a range with no cause. */
  crosstalk: number;
  /** Poisson rate of clutter along the ray, in objects per metre. */
  clutterRate: number;
  /** Time-of-flight jitter about the true range, in metres. */
  sigma: number;
}

const QUIET: Physics = { dropout: 0.05, crosstalk: 0.04, clutterRate: 0.012, sigma: 0.11 };
const BUSY: Physics = { dropout: 0.05, crosstalk: 0.04, clutterRate: 0.06, sigma: 0.11 };

/** The mixture weights the generator is *actually* using, in closed form. */
function trueWeights(p: Physics): { zHit: number; zShort: number; zMax: number; zRand: number } {
  const zMax = p.dropout;
  const zRand = (1 - p.dropout) * p.crosstalk;
  const survive = (1 - p.dropout) * (1 - p.crosstalk);
  // A homogeneous Poisson clutter field of rate λ hits the ray before the wall
  // with probability 1 − e^{−λ z*}; its nearest hit is Exp(λ) truncated at z*.
  const pClutter = 1 - Math.exp(-p.clutterRate * Z_STAR);
  return {
    zHit: survive * (1 - pClutter),
    zShort: survive * pClutter,
    zMax,
    zRand,
  };
}

const START_PARAMS: BeamParams = {
  zHit: 0.25,
  zShort: 0.25,
  zMax: 0.25,
  zRand: 0.25,
  sigmaHit: 0.4,
  lambdaShort: 0.5,
  maxRange: MAX_RANGE,
};

type Cause = 'hit' | 'short' | 'max' | 'rand';

interface Draw {
  z: number;
  cause: Cause;
  /** Where the clutter objects were on this shot, for the beam strip. */
  clutter: number[];
}

interface State {
  rng: Rng;
  params: BeamParams;
  physics: Physics;
  z: number[];
  counts: Float64Array;
  phase: 'collect' | 'fit' | 'done';
  emIter: number;
  logLik: number[];
  last: Draw;
}

/** One beam, generated by the world rather than by the model. */
function fireBeam(rng: Rng, phys: Physics): Draw {
  const clutter: number[] = [];
  // Thin the Poisson field to the visible segment [0, z*].
  const expected = phys.clutterRate * Z_STAR;
  const n = Math.min(6, poisson(rng, expected));
  for (let i = 0; i < n; i++) clutter.push(rng.uniform(0, Z_STAR));

  if (rng.next() < phys.dropout) return { z: MAX_RANGE, cause: 'max', clutter };
  if (rng.next() < phys.crosstalk) return { z: rng.uniform(0, MAX_RANGE), cause: 'rand', clutter };

  const nearest = clutter.length > 0 ? Math.min(...clutter) : Infinity;
  if (nearest < Z_STAR) {
    return { z: Math.max(0, nearest + rng.normal(0, phys.sigma * 0.5)), cause: 'short', clutter };
  }
  const z = Math.max(0, Math.min(MAX_RANGE, Z_STAR + rng.normal(0, phys.sigma)));
  return { z, cause: 'hit', clutter };
}

/** Knuth's method; the counts here are tiny, so the loop is cheap. */
function poisson(rng: Rng, lambda: number): number {
  if (lambda <= 0) return 0;
  const limit = Math.exp(-lambda);
  let k = 0;
  let p = 1;
  do {
    k++;
    p *= rng.next();
  } while (p > limit);
  return k - 1;
}

export function BeamMixtureMixer() {
  const [busy, setBusy] = useState(false);

  const init = useCallback(
    (seed: number): State => ({
      rng: new Rng(seed),
      params: { ...START_PARAMS },
      physics: busy ? BUSY : QUIET,
      z: [],
      counts: new Float64Array(BINS),
      phase: 'collect',
      emIter: 0,
      logLik: [],
      last: { z: Z_STAR, cause: 'hit', clutter: [] },
    }),
    [busy],
  );

  const step = useCallback((s: State): State => {
    if (s.phase === 'fit') {
      const out = emStep(s.z, s.z.map(() => Z_STAR), s.params);
      const emIter = s.emIter + 1;
      return {
        ...s,
        params: out.params,
        logLik: [...s.logLik, out.logLik],
        emIter,
        phase: emIter >= EM_ITERS ? 'done' : 'fit',
      };
    }

    // Collecting: fire a batch of beams into the histogram.
    const counts = Float64Array.from(s.counts);
    const z = s.z.slice();
    let last = s.last;
    for (let i = 0; i < BATCH; i++) {
      last = fireBeam(s.rng, s.physics);
      z.push(last.z);
      const bin = Math.min(BINS - 1, Math.floor((last.z / MAX_RANGE) * BINS));
      counts[bin] += 1;
    }
    // Autoplay teaches without a click: once enough data is in, fit once.
    const phase = s.phase === 'collect' && z.length >= TARGET ? 'fit' : s.phase;
    return { ...s, z, counts, last, phase, emIter: phase === 'fit' ? 0 : s.emIter, logLik: phase === 'fit' ? [] : s.logLik };
  }, []);

  const sim = useSimulation<State>({ init, step, fps: 12, initialSeed: 10 });
  const { state, setState } = sim;
  const p = state.params;

  const setParam = useCallback(
    (patch: Partial<BeamParams>) =>
      setState((s) => ({ ...s, params: { ...s.params, ...patch }, phase: s.phase === 'fit' ? 'done' : s.phase })),
    [setState],
  );

  const truth = useMemo(() => trueWeights(state.physics), [state.physics]);

  const draw = useCallback(
    (ctx: CanvasRenderingContext2D, v: Viewport, pal: Palette) => {
      clear(ctx, v, pal);
      const { counts, z, last, params } = state;
      const n = z.length;

      const stripY = 0.9; // the beam, drawn on the same range axis as the histogram
      const histTop = 0.72;
      const histBottom = 0.06;
      const baseY = sy(v, histBottom);
      const topY = sy(v, histTop);
      const h = baseY - topY;

      // ---- the beam, in range coordinates ------------------------------
      const stripPix = sy(v, stripY);
      ctx.strokeStyle = pal.grid;
      ctx.lineWidth = 1;
      ctx.beginPath();
      ctx.moveTo(sx(v, 0), stripPix);
      ctx.lineTo(sx(v, MAX_RANGE), stripPix);
      ctx.stroke();

      // The wall the map predicts: z*, gray dashed, because it is ground truth.
      ctx.strokeStyle = pal.truth;
      ctx.lineWidth = 2;
      ctx.setLineDash([5, 4]);
      ctx.beginPath();
      ctx.moveTo(sx(v, Z_STAR), stripPix - 14);
      ctx.lineTo(sx(v, Z_STAR), baseY);
      ctx.stroke();
      ctx.setLineDash([]);
      label(ctx, 'z* (wall)', sx(v, Z_STAR) + 5, stripPix - 8, pal.truth, { size: 10 });

      // Rusty, at range zero.
      ctx.fillStyle = pal.truth;
      ctx.beginPath();
      ctx.arc(sx(v, 0), stripPix, 4.5, 0, Math.PI * 2);
      ctx.fill();

      // Clutter on this shot: the Poisson field along the ray.
      ctx.fillStyle = pal.measurement;
      ctx.globalAlpha = 0.5;
      for (const c of last.clutter) {
        ctx.beginPath();
        ctx.arc(sx(v, c), stripPix, 3, 0, Math.PI * 2);
        ctx.fill();
      }
      ctx.globalAlpha = 1;

      // The reading itself.
      ctx.strokeStyle = pal.measurement;
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(sx(v, 0), stripPix);
      ctx.lineTo(sx(v, last.z), stripPix);
      ctx.stroke();
      ctx.beginPath();
      ctx.arc(sx(v, last.z), stripPix, 3.5, 0, Math.PI * 2);
      ctx.fillStyle = pal.measurement;
      ctx.fill();
      label(ctx, `z = ${last.z.toFixed(2)} m  · ${last.cause}`, sx(v, 0.1), stripPix - 12, pal.measurement, {
        size: 10,
        weight: 600,
      });

      if (n === 0) return;

      // ---- histogram, as a density ------------------------------------
      const binW = MAX_RANGE / BINS;
      const dens = Array.from(counts, (c) => c / (n * binW));
      // The model curve, sampled at bin centres, plus the max-range point mass.
      const model: number[] = [];
      for (let i = 0; i < BINS; i++) {
        const zc = (i + 0.5) * binW;
        model.push(beamLikelihood(zc, Z_STAR, params));
      }
      // p_max is a point mass, not a density; to share the axis it is drawn as
      // if its mass were spread over the last bin.
      const maxSpike = params.zMax / binW;
      const peak = Math.max(...dens, ...model, maxSpike, 1e-6);

      const barW = sl(v, binW);
      // Histogram bars: the data.
      ctx.fillStyle = pal.measurement;
      ctx.globalAlpha = 0.28;
      for (let i = 0; i < BINS; i++) {
        const bh = (dens[i] / peak) * h;
        ctx.fillRect(sx(v, i * binW), baseY - bh, Math.max(barW - 1, 1), bh);
      }
      ctx.globalAlpha = 1;

      // The four components, stacked as tinted areas: the model.
      const comps = ['hit', 'short', 'rand'] as const;
      const alphas: Record<(typeof comps)[number], number> = { hit: 0.55, short: 0.4, rand: 0.25 };
      const weightOf: Record<(typeof comps)[number], number> = {
        hit: params.zHit,
        short: params.zShort,
        rand: params.zRand,
      };
      for (const c of comps) {
        ctx.fillStyle = pal.measurement;
        ctx.globalAlpha = alphas[c];
        ctx.beginPath();
        ctx.moveTo(sx(v, 0), baseY);
        for (let i = 0; i < BINS; i++) {
          const zc = (i + 0.5) * binW;
          const comp = beamComponents(zc, Z_STAR, params);
          const val = weightOf[c] * comp[c];
          ctx.lineTo(sx(v, zc), baseY - (val / peak) * h);
        }
        ctx.lineTo(sx(v, MAX_RANGE), baseY);
        ctx.closePath();
        ctx.fill();
      }
      ctx.globalAlpha = 1;

      // p_max is a point mass: draw it as what it is, a spike.
      const spikeH = Math.min((maxSpike / peak) * h, h);
      ctx.strokeStyle = pal.measurement;
      ctx.lineWidth = 3;
      ctx.beginPath();
      ctx.moveTo(sx(v, MAX_RANGE) - 2, baseY);
      ctx.lineTo(sx(v, MAX_RANGE) - 2, baseY - spikeH);
      ctx.stroke();
      label(ctx, 'z_max', sx(v, MAX_RANGE) - 6, baseY - spikeH - 9, pal.measurement, {
        size: 10,
        align: 'right',
      });

      // The mixture itself, on top.
      ctx.strokeStyle = pal.measurement;
      ctx.lineWidth = 2;
      ctx.beginPath();
      for (let i = 0; i < BINS; i++) {
        const y = baseY - (model[i] / peak) * h;
        if (i === 0) ctx.moveTo(sx(v, (i + 0.5) * binW), y);
        else ctx.lineTo(sx(v, (i + 0.5) * binW), y);
      }
      ctx.stroke();

      // Baseline and axis ticks.
      ctx.strokeStyle = pal.grid;
      ctx.lineWidth = 1;
      ctx.beginPath();
      ctx.moveTo(sx(v, 0), baseY);
      ctx.lineTo(sx(v, MAX_RANGE), baseY);
      ctx.stroke();
      for (let m = 0; m <= MAX_RANGE; m += 2) {
        label(ctx, `${m}`, sx(v, m), baseY + 10, pal.ink, { size: 9, align: 'center' });
      }

      const caption =
        state.phase === 'fit'
          ? `EM iteration ${state.emIter}/${EM_ITERS}`
          : state.phase === 'done'
            ? 'fitted — drag a slider to take over'
            : `collecting: ${n} beams`;
      label(ctx, caption, sx(v, 0.1), topY - 8, pal.ink, { size: 10, weight: 600 });
    },
    [state],
  );

  const ll = state.logLik.length > 0 ? state.logLik[state.logLik.length - 1] : null;

  return (
    <WidgetFrame
      id="w10.1"
      title="The Beam Mixture Mixer"
      teaches="Sensor noise is not a Gaussian around the true range. It is four causes stacked, and their weights can be learned from data."
      colorKey={['measurement', 'truth']}
      caption={
        <>
          One beam, fired down the corridor over and over. The strip at the top is that beam in range
          coordinates — the same axis as the histogram below it, so every reading drops straight into
          its bin. The dashed gray line is <em>z*</em>, the range the map predicts. Watch the four
          features appear: a hump at the wall, a shoulder in front of it whenever a clutter object
          intercepts the ray first, a spike piled up at <em>z</em><sub>max</sub> from dropouts, and a
          thin floor from crosstalk. After 4 500 beams the widget runs EM (Table 6.2) and the four
          weights animate onto the data — compare the fitted row with the generator&rsquo;s true row.
          Then turn on <strong>people in the corridor</strong> and press Fit again: predict first
          which two numbers move.
        </>
      }
    >
      <SimCanvas
        world={{ minX: -0.25, maxX: MAX_RANGE + 0.25, minY: 0, maxY: 1 }}
        draw={draw}
        deps={[sim.tick, state]}
        aspect={2.3}
        padding={0}
        ariaLabel="A histogram of ten thousand range readings from a single laser beam, showing a Gaussian hump at the wall distance, an exponential shoulder in front of it, a spike at maximum range and a uniform floor, with the fitted four-component mixture drawn over it."
      />

      <div className="grid grid-cols-2 divide-x divide-fd-border border-t border-fd-border text-center sm:grid-cols-4">
        <WeightStat label="z_hit" fitted={p.zHit} truth={truth.zHit} />
        <WeightStat label="z_short" fitted={p.zShort} truth={truth.zShort} />
        <WeightStat label="z_max" fitted={p.zMax} truth={truth.zMax} />
        <WeightStat label="z_rand" fitted={p.zRand} truth={truth.zRand} />
      </div>
      <div className="grid grid-cols-3 divide-x divide-fd-border border-t border-fd-border text-center">
        <Stat label="beams" value={String(state.z.length)} />
        <Stat label="σ̂_hit" value={`${p.sigmaHit.toFixed(3)} m`} />
        <Stat label="log-lik / beam" value={ll === null ? '—' : ll.toFixed(4)} />
      </div>

      <ControlPanel columns={3}>
        <Slider
          label="σ_hit"
          role="measurement"
          value={p.sigmaHit}
          min={0.02}
          max={0.8}
          step={0.01}
          unit="m"
          onChange={(v) => setParam({ sigmaHit: v })}
          help="Width of the hit peak. EM sets this from the data; drag it to see the fit break."
        />
        <Slider
          label="λ_short"
          value={p.lambdaShort}
          min={0.05}
          max={4}
          step={0.05}
          onChange={(v) => setParam({ lambdaShort: v })}
          help="Decay rate of the unexpected-obstacle shoulder, in 1/m."
        />
        <Slider
          label="z_hit"
          value={p.zHit}
          min={0}
          max={1}
          step={0.01}
          onChange={(v) => setParam(renormalize(p, 'zHit', v))}
        />
        <Slider
          label="z_short"
          value={p.zShort}
          min={0}
          max={1}
          step={0.01}
          onChange={(v) => setParam(renormalize(p, 'zShort', v))}
        />
        <Slider
          label="z_max"
          value={p.zMax}
          min={0}
          max={1}
          step={0.01}
          onChange={(v) => setParam(renormalize(p, 'zMax', v))}
        />
        <Slider
          label="z_rand"
          value={p.zRand}
          min={0}
          max={1}
          step={0.01}
          onChange={(v) => setParam(renormalize(p, 'zRand', v))}
        />
        <Toggle
          label="People in the corridor"
          role="measurement"
          checked={busy}
          onChange={(v) => {
            setBusy(v);
            setState((s) => ({
              ...s,
              physics: v ? BUSY : QUIET,
              z: [],
              counts: new Float64Array(BINS),
              phase: 'collect',
              logLik: [],
              emIter: 0,
            }));
          }}
        />
      </ControlPanel>

      <div className="border-t border-fd-border px-3 py-2">
        <ButtonRow>
          <ActionButton
            emphasis
            onClick={() => setState((s) => ({ ...s, phase: 'fit', emIter: 0, logLik: [] }))}
          >
            Fit (EM)
          </ActionButton>
          <ActionButton
            onClick={() => setState((s) => ({ ...s, params: { ...START_PARAMS }, phase: 'done', logLik: [] }))}
          >
            Reset Θ
          </ActionButton>
          <ActionButton
            onClick={() =>
              setState((s) => ({ ...s, z: [], counts: new Float64Array(BINS), phase: 'collect' }))
            }
          >
            Clear data
          </ActionButton>
        </ButtonRow>
      </div>

      <Transport
        playing={sim.playing}
        onToggle={sim.toggle}
        onStep={sim.stepOnce}
        onReset={sim.reset}
        onReseed={() => sim.reseed()}
        seed={sim.seed}
        tick={sim.tick}
      />
    </WidgetFrame>
  );
}

type WeightKey = 'zHit' | 'zShort' | 'zMax' | 'zRand';
const WEIGHT_KEYS: WeightKey[] = ['zHit', 'zShort', 'zMax', 'zRand'];

/** Move one weight and rescale the other three: the simplex has three degrees of freedom. */
function renormalize(p: BeamParams, key: WeightKey, value: number): Partial<BeamParams> {
  const others = WEIGHT_KEYS.filter((k) => k !== key);
  const rest = others.reduce((a, k) => a + p[k], 0);
  const target = 1 - value;
  const scaled = (k: WeightKey) => (rest > 1e-9 ? (p[k] / rest) * target : target / 3);
  const out: Record<WeightKey, number> = {
    zHit: key === 'zHit' ? value : scaled('zHit'),
    zShort: key === 'zShort' ? value : scaled('zShort'),
    zMax: key === 'zMax' ? value : scaled('zMax'),
    zRand: key === 'zRand' ? value : scaled('zRand'),
  };
  return out;
}

function Stat({ label: l, value }: { label: string; value: string }) {
  return (
    <div className="px-2 py-1.5">
      <div className="eyebrow">{l}</div>
      <div className="font-mono text-sm tabular-nums">{value}</div>
    </div>
  );
}

function WeightStat({ label: l, fitted, truth }: { label: string; fitted: number; truth: number }) {
  return (
    <div className="px-2 py-1.5">
      <div className="eyebrow">{l}</div>
      <div className="font-mono text-sm tabular-nums" style={{ color: 'var(--pr-measurement)' }}>
        {fitted.toFixed(3)}
      </div>
      <div className="font-mono text-[0.65rem] tabular-nums text-fd-muted-foreground">
        true {truth.toFixed(3)}
      </div>
    </div>
  );
}
